---
- hosts: packer
  roles:
    - aptget-update
    - for-jenkins-connection
    - install-fundamental-tools
    - install-package-for-build
    - install-vagrant-stack
    - install-packer-build-stack
    - install-ansible
    - tmp-clean
