---
- hosts: prgate
  roles:
    - aptget-update
    - for-jenkins-connection
    - install-fundamental-tools
    - install-package-for-build
    - install-rackhd-dependency
    - install-package-for-ci
    - install-vagrant-stack
    - install-python-tools
    - mount-isofarm
    - setup-static-file-server
    - fix-apt-dependency
    - install-docker
    - install-ansible
